In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]
a = np.array(list1)

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0])

(2, 3)
1


In [5]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a = arr[1:,1:]
print(a)

[[5 6]
 [8 9]]


In [7]:
a = arr[0:2,0:2]
print(a)

[[1 2]
 [4 5]]


In [8]:
a = arr[1:,1:]
print(a)

[[5 6]
 [8 9]]


In [9]:
bool_array = np.array([[False, True, False],[True, False, True],[False, True, False]])
bool_array

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [10]:
n = arr[bool_array]
print(n)

[2 4 6 8]


In [11]:
a = np.array(lst)
bool_indexing = (a % 2 == 0)
print(bool_indexing)
print(a[bool_indexing])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [14]:
print(a[bool_indexing])
n = a[a % 2 == 0]

[2 4 6 8]


In [23]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [22]:
b = np.arange(4,8).reshape(2,2)
b

array([[4, 5],
       [6, 7]])

In [24]:
c = a + b
c = np.add(a,b)
print(c)

[[ 4  6]
 [ 8 10]]


In [25]:
c = a - b
c = np.subtract(a,b)
print(c)

[[-4 -4]
 [-4 -4]]


In [26]:
c = a * b
c = np.multiply(a,b)
print(c)

[[ 0  5]
 [12 21]]


In [27]:
c = a / b
c = np.divide(a,b)
print(c)

[[0.         0.2       ]
 [0.33333333 0.42857143]]


In [28]:
import pandas as pd
from pandas import Series, DataFrame

In [30]:
ar1 = np.arange(4)
ar1

array([0, 1, 2, 3])

In [31]:
ar1 = np.arange(4).reshape(2,2)
ar1

array([[0, 1],
       [2, 3]])

In [34]:
np.concatenate([ar1,ar1],axis=0)

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [33]:
np.concatenate([ar1,ar1],axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [40]:
df1 = DataFrame({'A':[1,2,3],'B':[4,5,6]})
df1

A  B
0  1  4
1  2  5
2  3  6

In [44]:
df2 = DataFrame({'A':[10,11],'B':[40,50]})
df2

A   B
0  10  40
1  11  50

In [42]:
df3 = DataFrame({'A':[40,50,60],'B':[70,80,90],'C':[10,11,12]})
df3

A   B   C
0  40  70  10
1  50  80  11
2  60  90  12

In [45]:
pd.concat([df1,df2])

A   B
0   1   4
1   2   5
2   3   6
0  10  40
1  11  50

In [46]:
pd.concat([df1,df2],axis=1)

A  B     A     B
0  1  4  10.0  40.0
1  2  5  11.0  50.0
2  3  6   NaN   NaN

In [47]:
pd.concat([df1,df2],axis=1, join = 'inner')

A  B   A   B
0  1  4  10  40
1  2  5  11  50

In [50]:
a=pd.concat([df1,df2],axis=1, join = 'inner', keys = ['one','two'])
a

one        two    
    A  B   C   A   B
0   1  5   9  10  40
1   2  6  10  11  50

In [51]:
b=pd.concat([df1,df2],axis=0, join = 'inner', keys = ['one','two'])
b

A   B
one 0   1   5
    1   2   6
    2   3   7
    3   4   8
two 0  10  40
    1  11  50

In [49]:
df1 = DataFrame({'A':[1,2,3,4],'B':[5,6,7,8],'C':[9,10,11,12]})
df1

A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [52]:
df2 = DataFrame({'A':['a','b','c','d'],'D':['e','f','g','h'],'E':['i','j','k','l']})
df2

A  D  E
0  a  e  i
1  b  f  j
2  c  g  k
3  d  h  l

In [54]:
df1.combine_first(df2)

A  B   C  D  E
0  1  5   9  e  i
1  2  6  10  f  j
2  3  7  11  g  k
3  4  8  12  h  l